CREATE DATABASE bileter
USE bileter
GO
CREATE TABLE Users(ID INT NOT NULL, eMail VARCHAR(50) NOT NULL, Pass VARCHAR(25) NOT NULL, RoleID INT NOT NULL) 
ALTER TABLE Users
ADD CONSTRAINT UserID_pk PRIMARY KEY (ID)
CREATE TABLE Hosters(ID INT NOT NULL, HosterName VARCHAR(30) NOT NULL, Company VARCHAR(50) NOT NULL) 
ALTER TABLE Hosters
ADD CONSTRAINT hostUserID_pk PRIMARY KEY (ID)
ALTER TABLE Hosters
ADD CONSTRAINT hostUserID_fk FOREIGN KEY (ID)
REFERENCES Users (ID)
CREATE TABLE Sellers(ID INT NOT NULL, FirstName VARCHAR(30) NOT NULL, LastName VARCHAR(30) NOT NULL, TotalSumm INT NOT NULL, TotalCount INT NOT NULL) -- Prodavci
ALTER TABLE Sellers 
ADD CONSTRAINT sellUserID_pk PRIMARY KEY (ID)
ALTER TABLE Sellers 
ADD CONSTRAINT sellUserID_fk FOREIGN KEY (ID)
REFERENCES Users (ID) 
CREATE TABLE Buyers(ID INT NOT NULL, FirstName VARCHAR(30) NOT NULL, LastName VARCHAR(30) NOT NULL, Ticket INT NOT NULL) -- Name and ID of ticket
ALTER TABLE Buyers 
ADD CONSTRAINT buyerUserID_pk PRIMARY KEY (ID)
ALTER TABLE Buyers 
ADD CONSTRAINT buyerUserID_fk FOREIGN KEY (ID)
REFERENCES Users (ID) 
CREATE TABLE CrEvents(ID INT NOT NULL, AgeLimit INT NOT NULL, EventName VARCHAR(50) NOT NULL, EventDesc VARCHAR(1000) NOT NULL, PlannedDate DATETIME NOT NULL, Cost INT NOT NULL, TicketsCount INT NOT NULL) -- Sozdanie eventi
ALTER TABLE CrEvents
ADD CONSTRAINT crevID_pk PRIMARY KEY (ID)
CREATE TABLE Tickets(ID INT NOT NULL, EventID INT NOT NULL, Buyer INT NOT NULL, Cost INT NOT NULL, aStatus INT NOT NULL, qrImage IMAGE NULL) 
ALTER TABLE Tickets 
ADD CONSTRAINT ticketID_pk PRIMARY KEY (ID)
ALTER TABLE Tickets 
ADD CONSTRAINT ticketID_fk FOREIGN KEY (EventID)
REFERENCES CrEvents (ID)
ALTER TABLE Buyers 
ADD CONSTRAINT ticketBuyerConnectionID_fk FOREIGN KEY (Ticket)
REFERENCES Tickets (ID) 
CREATE TABLE Roles (ID INT NOT NULL, Title VARCHAR(30))
ALTER TABLE Roles 
ADD CONSTRAINT roleID_pk PRIMARY KEY (ID)
ALTER TABLE Users 
ADD CONSTRAINT roleID_fk FOREIGN KEY (RoleID)
REFERENCES Roles (ID) 


